name: 'Maintainers Housekeeper'
description: 'a helpful hand for maintainers'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  token:
    description: 'GitHub token'
    required: true
  issue_number:
    description: 'Branch name'
    required: true
  issue_title:
    description: 'Issue title'
    required: true
  issue_body:
    description: 'Issue body'
    required: true
  base_branch:
    description: 'Base branch'
    default: 'main'